version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /
    ignore:
      - dependency-name: async
        versions: [">=2"]
    schedule:
      interval: daily
