name: Commit

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build OCI Image
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [alpine, debian]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Install Cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1

      - name: Run Hadolint
        id: hadolint
        uses: hadolint/hadolint-action@4b5806eb9c6bee4954fc0e0cc3ad6175fc9782c1 # v3.0.0
        continue-on-error: true
        with:
          dockerfile: ./${{ matrix.os }}.dockerfile
          format: sarif
          output-file: hadolint.sarif
          no-fail: false

      - name: Upload Hadolint SARIF report
        uses: github/codeql-action/upload-sarif@515828d97454b8354517688ddc5b48402b723750 # v2.1.38
        with:
          category: hadolint-${{ matrix.os }}
          sarif_file: hadolint.sarif

      - name: Generate OCI image metadata
        id: metadata
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
        with:
          flavor: |
            latest=false
          images: |
            ghcr.io/${{ github.repository }}
            docker.io/${{ secrets.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=${{ matrix.os }}-main
            type=raw,value=main,enable=${{ matrix.os == 'alpine' }}
          labels: |
            org.opencontainers.image.description=Fluentd aggregator OCI image based on the default Fluentd OCI image.
            org.opencontainers.image.authors=Fluentd developers <fluentd@googlegroups.com>

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # v2.2.1

      - name: Build OCI image
        id: build
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 # v3.3.0
        with:
          file: ./${{ matrix.os }}.dockerfile
          context: .
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          load: true
          push: false

      - name: Generate OCI image Syft SBOM
        uses: anchore/sbom-action@06e109483e6aa305a2b2395eabae554e51530e1d # v0.13.1
        with:
          image: "ghcr.io/${{ github.repository }}:${{ steps.metadata.outputs.version }}"
          dependency-snapshot: true
          format: spdx-json
          artifact-name: ${{ github.event.repository.name }}-${{ matrix.os }}-syft-sbom
          output-file: ${{ github.event.repository.name }}-${{ matrix.os }}-syft-sbom.spdx.json

      - name: Scan OCI image Syft SBOM with Grype
        id: scan
        uses: anchore/scan-action@9a22e4caae42db0d4c687ab5431e1c3699d0def1 # v3.3.2
        continue-on-error: true
        with:
          sbom: ${{ github.event.repository.name }}-${{ matrix.os }}-syft-sbom.spdx.json
          severity-cutoff: medium
          output-format: sarif
          fail-build: true

      - name: Upload Grype SARIF report
        uses: github/codeql-action/upload-sarif@515828d97454b8354517688ddc5b48402b723750 # v2.1.38
        with:
          category: grype-${{ matrix.os }}
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Fail workflow
        if: ${{ steps.hadolint.outcome == 'failure' && steps.scan.outcome == 'failure' }}
        run: |
          set -euo pipefail
          echo "::error::Code scanning failed."
          exit 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push OCI image
        id: build_push
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 # v3.3.0
        with:
          file: ./${{ matrix.os }}.dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          load: false
          push: true

      - name: Sign OCI image
        env:
          COSIGN_EXPERIMENTAL: true
        run: echo "${{ steps.metadata.outputs.tags }}" | xargs -I {} cosign sign --yes --recursive {}@${{ steps.build_push.outputs.digest }}
