name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    strategy:
      fail-fast: false
      matrix:
        os: [alpine, debian]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./${{ matrix.os }}.dockerfile
          context: .
          platforms: linux/amd64
          push: false
