name: Release

on:
  push:
    tags:
      - v*

concurrency:
  group: release
  cancel-in-progress: false

permissions: read-all

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    outputs:
      version: ${{ steps.setup.outputs.version }}
    steps:
      - name: Setup
        id: setup
        run: |
          set -euo pipefail

          ref_name="${{ github.ref_name }}"
          version="${ref_name/v/}"

          echo "version=${version}" >> "${GITHUB_OUTPUT}"

  build:
    name: Build
    uses: action-stars/build-workflows/.github/workflows/build-oci-image.yaml@edcb1cca0ace2b51717e08992963b84c7e13b719 # v0.13.0
    needs: setup
    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write
      packages: write
      security-events: write
    with:
      name: ${{ github.event.repository.name }}
      repository: ${{ github.repository_owner }}
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64
      labels: |
        org.opencontainers.image.description=Fluentd aggregator OCI image based on the default Fluentd OCI image.
        org.opencontainers.image.authors=Fluentd developers <fluentd@googlegroups.com>
      tags: ${{ format('{0},latest', needs.setup.outputs.version) }}
      scan_image: true
      push_sbom: true
      push_sarif: true
      push_image: true

  docker:
    name: Docker Hub
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Install ghactl
        uses: action-stars/ghactl-action@ee93644a33e63f19d4af8cee920710fdff236af8 # v0.1.0
        with:
          token: ${{ github.token }}
          version: latest

      - name: Install tools
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          ghactl tool install --owner oras-project --repo oras --version latest

      - name: Login to DockerHub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        env:
          INPUT_IMAGE: ${{ needs.build.outputs.image }}
          INPUT_DIGEST: ${{ needs.build.outputs.digest }}
          INPUT_TAGS: ${{ needs.build.outputs.tags }}
        run: |
          set -euo pipefail

          docker_hub_image="docker.io/fluent/fluentd-aggregator"

          # shellcheck disable=SC2016
          for tag in ${INPUT_TAGS//,/ }; do
            oras cp --recursive "${INPUT_IMAGE}@${INPUT_DIGEST}" "${docker_hub_image}:${tag}"
          done

  publish:
    name: Publish Release
    needs: [setup, build, docker]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@1faaf50aa09d5793d9a100819973df801febfb31 # v2.4.0
        with:
          path: ./CHANGELOG.md
          version: ${{ github.ref_name }}

      - name: Create release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          token: ${{ github.token }}
          makeLatest: true
          body: ${{ steps.changelog_reader.outputs.changes }}
          allowUpdates: false
